// Namco NB-1 MiSTer core -- board configuration record (M7).
// Copyright (C) 2026 Kyle Lester. SPDX-License-Identifier: GPL-3.0-or-later
//
// Receives the MRA's board configuration record on ioctl index 2 and holds
// the fields the platform RTL needs. The record describes the HARDWARE
// fitted to a game's board (for M7: which KEYCUS part and on which words it
// answers); nothing here identifies a game. Generated by
// scripts/mra/nb1_mra.py from scripts/mra/games/<set>.json; the format and
// the per-game values are in docs/M7_RESEARCH.md section 6.
//
// Record, 16 bytes, little-endian fields:
//   0-3   "NB1B"
//   4     version = 1, 2 (M16) or 3 (M25)
//   5     record length in bytes = 16
//   6-7   0
//   8     KEYCUS mode: 0 = no KEYCUS answer (every word reads $0000),
//                      1 = ID word + changing word (C3xx "ID + random")
//   9     KEYCUS ID word index (0-15; byte address $6E0000 + 2 * index)
//   10-11 KEYCUS ID value (the part number in binary, e.g. C366 = $016E)
//   12    KEYCUS changing-word index (0-15)
//   13    version 2: the game's orientation, MAME ROT in quarter turns clockwise
//         (0 = ROT0, 1 = ROT90, 2 = ROT180, 3 = ROT270; M16 control composition,
//         nb1_orientation); version 1: 0
//   14    version 3: the I/O board fitted (0 = none, 1 = light-gun board read at $100000, Point Blank /
//         Gun Bullet: nb1_gun); versions 1-2: 0
//   15    0
//
// Timing: the fields are taken only when the index-2 download ENDS, and
// only if the whole record is present and valid. Every download holds the
// CPU in reset (NB1.sv reset_request), so the CPU never sees a field change.
// A new index-2 download invalidates the record at its start. PLL loss of
// lock (init) forgets it. Failure behaviour: with no record, or an invalid
// one (bad magic/version/length, mode > 1, a word index > 15), record_ok
// stays low and the KEYCUS answers as mode 0 (all words $0000, writes
// ignored) -- the game's own KEYCUS check then fails visibly, which the
// overlay's KCF row reports as NONE or BAD. game_rot: from a version-2
// record; otherwise (version 1, no or bad record) ROT90, the orientation M14
// assumed, so an M14/M15 MRA keeps its control mapping.
module nb1_board_config #(
    parameter [15:0] INDEX = 16'd2
) (
    input  wire        clk_sys,
    input  wire        init,

    input  wire        ioctl_download,
    input  wire [15:0] ioctl_index,
    input  wire        ioctl_wr,
    input  wire [26:0] ioctl_addr,
    input  wire [15:0] ioctl_dout,        // WIDE=1: [7:0] = byte at addr, [15:8] = byte at addr+1

    output reg         record_ok   = 1'b0,   // a valid record is in force
    output reg         record_seen = 1'b0,   // an index-2 download has completed (valid or not)
    output reg  [7:0]  kc_mode     = 8'd0,
    output reg  [3:0]  kc_id_word  = 4'd0,
    output reg  [15:0] kc_id       = 16'd0,
    output reg  [3:0]  kc_rnd_word = 4'd0,
    output reg  [1:0]  game_rot    = 2'd1,    // M16: quarter turns CW (default ROT90, see above)
    output reg         io_gun      = 1'b0     // M25: light-gun I/O board (version 3, byte 14 = 1)
);
    wire sel = ioctl_download && (ioctl_index == INDEX);
    reg  sel_q = 1'b0;

    // staging: record words 0..7 (byte 2k in [7:0]) and which were written
    reg [15:0] w [0:7];
    reg [7:0]  got = 8'd0;

    wire hdr_ok = (w[0] == 16'h424E) && (w[1] == 16'h4231) &&     // "NB1B"
                  ((w[2] == 16'h1001) || (w[2] == 16'h1002) || (w[2] == 16'h1003)) &&   // version 1-3, length 16
                  (w[3] == 16'h0000);
    wire v2     = (w[2][7:0] >= 8'd2);
    wire v3     = (w[2][7:0] == 8'd3);
    wire fld_ok = (w[4][7:0] <= 8'd1) &&                          // mode 0 or 1
                  (w[4][15:12] == 4'd0) &&                        // ID word 0-15
                  (w[6][7:4] == 4'd0) &&                          // changing word 0-15
                  (v2 ? (w[6][15:8] <= 8'd3) : (w[6][15:8] == 8'd0)) &&   // v2: orientation 0-3
                  (v3 ? (w[7][7:0] <= 8'd1 && w[7][15:8] == 8'd0) : (w[7] == 16'h0000));
    wire valid  = (got == 8'hFF) && hdr_ok && fld_ok;

    always @(posedge clk_sys) begin
        if (init) begin
            sel_q <= 1'b0; got <= 8'd0;
            record_ok <= 1'b0; record_seen <= 1'b0;
            kc_mode <= 8'd0; kc_id_word <= 4'd0; kc_id <= 16'd0; kc_rnd_word <= 4'd0; game_rot <= 2'd1; io_gun <= 1'b0;
        end else begin
            sel_q <= sel;
            if (sel && !sel_q) begin                 // a new record is arriving
                got       <= 8'd0;
                record_ok <= 1'b0;
                kc_mode   <= 8'd0;
            end
            if (sel && ioctl_wr && ioctl_addr[26:4] == 23'd0) begin
                w[ioctl_addr[3:1]]   <= ioctl_dout;
                got[ioctl_addr[3:1]] <= 1'b1;
            end
            if (!sel && sel_q) begin                 // download finished: commit or reject
                record_seen <= 1'b1;
                record_ok   <= valid;
                kc_mode     <= valid ? w[4][7:0]  : 8'd0;
                kc_id_word  <= valid ? w[4][11:8] : 4'd0;
                kc_id       <= valid ? w[5]       : 16'd0;
                kc_rnd_word <= valid ? w[6][3:0]  : 4'd0;
                game_rot    <= (valid && v2) ? w[6][9:8] : 2'd1;
                io_gun      <= valid && v3 && w[7][0];
            end
        end
    end
endmodule
