// Namco NB-2 MiSTer core -- ROM read-back checker.
// Copyright (C) 2026 Kyle Lester. SPDX-License-Identifier: GPL-3.0-or-later
//
// The NB-1 core's nb1_rom_check (docs/PROVENANCE.md) with the NB-2 changes: record magic "NB2C", 26-bit
// offsets (nb2_mem_pkg), the OBJ region read from the DDR3 sprite store (second client port obj_*), and the
// lane code 0x12: one CRC over bytes 1, 0, 3, 2 of every longword (a ROM_LOAD16_WORD_SWAP file, whose window
// holds the file with the bytes of every 16-bit word exchanged; the CRC then equals the file's CRC32).
// The NB-1 description follows.
//
// Proves the whole path MRA -> ioctl -> loader -> nb1_memory -> SDRAM ->
// client read. After a ROM download it reads storage back through an
// ordinary nb1_memory client port and computes zip-compatible CRC32s
// (reflected, poly 0xEDB88320, init/final 0xFFFFFFFF).
//
// The expected values are NOT in the RTL. They arrive as a "check record"
// in a separate ioctl index (MRA data), so the RBF stays game-independent.
// For an interleaved region, each lane of a 32-bit word is its own CRC: a
// ROM_LOAD32_WORD pair gives two lanes (bytes 0-1 and 2-3 of every
// longword), so each lane's CRC equals the CRC32 MAME lists for that EPROM
// file. That checks byte-lane placement against MAME metadata directly.
//
// Check record (little-endian fields; generated by scripts/mra/nb1_mra.py):
//   header, 32 bytes:  "NB1C", version=1, entry count (<=32), 2 x 0,
//                      expected index-0 stream length (u32), 20 x 0
//   entry,  32 bytes:  region id (u8), lanes (u8: 1, 2 or 4), 2 x 0,
//                      offset (u32, multiple of 4), length (u32, multiple of 4),
//                      crc lane0..lane3 (4 x u32), 4 x 0
// Lane of byte k (k=0 is offset+0, the MSB lane) = k*lanes/4.
//
// The record and the per-entry results are diagnostics only. The checker
// re-runs after every reset release (reset includes downloads and the OSD
// reset), which is how the hardware test shows that resets do not corrupt
// loaded data. `restart` re-runs it on demand.
module nb2_rom_check #(
    parameter [15:0] INDEX       = 16'd3,
    parameter int    MAX_ENTRIES = 32
) (
    input  wire        clk_sys,
    input  wire        init,        // PLL loss of lock: forget the record
    input  wire        reset,       // runtime reset (reset_sys): abort/restart run
    input  wire        restart,

    input  wire        ioctl_download,
    input  wire [15:0] ioctl_index,
    input  wire        ioctl_wr,
    input  wire [26:0] ioctl_addr,
    input  wire [15:0] ioctl_dout,

    input  wire        rom_loaded,
    input  wire [26:0] stream_bytes,

    // nb2_memory client port (read-only use) and the DDR3 sprite store port, chosen by region
    output wire        sd_valid,
    input  wire        sd_ready,
    input  wire        sd_rsp_valid,
    input  wire [31:0] sd_rsp_rdata,
    input  wire        sd_rsp_err,
    output wire        obj_valid,
    input  wire        obj_ready,
    input  wire        obj_rsp_valid,
    input  wire [31:0] obj_rsp_rdata,
    input  wire        obj_rsp_err,
    output wire [3:0]  req_region,
    output wire [25:0] req_offset,
    output wire        req_we,
    output wire [31:0] req_wdata,
    output wire [3:0]  req_be,

    output reg                      record_ok   = 1'b0,
    output reg  [5:0]               entry_count = '0,
    output reg  [2*MAX_ENTRIES-1:0] entry_status = '0, // per entry: 0 pending, 1 running, 2 pass, 3 fail
    output reg                      running     = 1'b0,
    output reg                      done        = 1'b0,
    output reg                      all_pass    = 1'b0,
    output reg                      length_ok   = 1'b0,
    output reg  [3:0]               run_count   = '0
);
    // ------------------------------------------------------------------
    // CRC32, one byte per call.
    function automatic [31:0] crc32_byte(input [31:0] crc, input [7:0] d);
        reg [31:0] c;
        c = crc ^ {24'd0, d};
        for (int i = 0; i < 8; i++) c = c[0] ? ((c >> 1) ^ 32'hEDB88320) : (c >> 1);
        return c;
    endfunction

    // ------------------------------------------------------------------
    // Record storage: 16-bit words, byte 2k in [7:0].
    localparam int REC_WORDS = 16 + 16 * MAX_ENTRIES;
    localparam int RAW = $clog2(REC_WORDS);

    reg [15:0] rec [0:REC_WORDS-1];
    reg [RAW-1:0] rec_raddr = '0;
    reg [15:0]    rec_q = '0;

    wire rec_sel = ioctl_download && (ioctl_index == INDEX);
    wire rec_wr  = rec_sel && ioctl_wr && (ioctl_addr[26:1] < REC_WORDS);

    always @(posedge clk_sys) begin
        if (rec_wr) rec[ioctl_addr[RAW:1]] <= ioctl_dout;
        rec_q <= rec[rec_raddr];
    end

    reg        rec_sel_q = 1'b0;
    reg [15:0] h_magic0 = '0, h_magic1 = '0, h_ver = '0;
    reg [31:0] exp_len = '0;

    always @(posedge clk_sys) begin
        if (init) begin
            rec_sel_q <= 1'b0; record_ok <= 1'b0; entry_count <= '0;
            h_magic0 <= '0; h_magic1 <= '0; h_ver <= '0; exp_len <= '0;
        end else begin
            rec_sel_q <= rec_sel;
            if (rec_sel && !rec_sel_q) begin
                record_ok <= 1'b0;
                h_magic0 <= '0; h_magic1 <= '0; h_ver <= '0; exp_len <= '0;
            end
            if (rec_sel && ioctl_wr) begin
                case (ioctl_addr)
                    27'd0: h_magic0 <= ioctl_dout;
                    27'd2: h_magic1 <= ioctl_dout;
                    27'd4: h_ver    <= ioctl_dout;
                    27'd8: exp_len[15:0]  <= ioctl_dout;
                    27'd10: exp_len[31:16] <= ioctl_dout;
                    default: ;
                endcase
            end
            if (!rec_sel && rec_sel_q) begin
                // "NB2C", version 1, count within limits
                record_ok   <= (h_magic0 == 16'h424E) && (h_magic1 == 16'h4332) &&
                               (h_ver[7:0] == 8'd1) && (h_ver[15:8] <= MAX_ENTRIES);
                entry_count <= (h_ver[15:8] <= MAX_ENTRIES) ? h_ver[13:8] : 6'd0;
            end
        end
    end

    // ------------------------------------------------------------------
    // Run engine.
    localparam [2:0] R_IDLE  = 3'd0,
                     R_FETCH = 3'd1,
                     R_READ  = 3'd2,
                     R_CMP   = 3'd3,
                     R_NEXT  = 3'd4,
                     R_DONE  = 3'd5;

    reg [2:0]  rstate = R_IDLE;
    reg [5:0]  entry = '0;
    reg [4:0]  fk = '0;               // fetch word counter
    reg [3:0]  e_region = '0;
    reg [7:0]  e_lanes = '0;
    reg [31:0] e_offset = '0, e_len = '0;
    reg [31:0] e_crc [0:3];
    reg [31:0] crc [0:3];
    reg        e_fail = 1'b0;
    reg [31:0] req_pos = '0;          // bytes requested so far
    reg [31:0] done_pos = '0;         // bytes processed so far
    reg        outstanding = 1'b0;
    reg        hold_full = 1'b0;
    reg [31:0] hold = '0;
    reg [31:0] proc = '0;
    reg [2:0]  proc_left = '0;        // bytes of `proc` still to process
    reg [1:0]  proc_k = '0;
    reg        armed = 1'b1;          // run once per reset release / restart

    // M22 timing: (req_pos < e_len) is kept in a register updated with req_pos, so the 32-bit compare no longer
    // sits in front of the memory arbiter's grant (identical request sequence).
    reg        more_q = 1'b0;
    wire   req_valid  = (rstate == R_READ) && !outstanding && !hold_full && more_q;
    wire   to_obj     = (e_region == nb2_mem_pkg::REG_OBJ);
    assign sd_valid   = req_valid && !to_obj;
    assign obj_valid  = req_valid && to_obj;
    wire   req_ready  = to_obj ? obj_ready : sd_ready;
    wire   rsp_valid  = to_obj ? obj_rsp_valid : sd_rsp_valid;
    wire [31:0] rsp_rdata = to_obj ? obj_rsp_rdata : sd_rsp_rdata;
    wire   rsp_err    = to_obj ? obj_rsp_err : sd_rsp_err;
    assign req_region = e_region;
    // timing: the request offset is a register (e_offset + req_pos kept up to date with req_pos), so no adder sits
    // in front of the memory scheduler's range check and grant (identical request sequence)
    reg [25:0] req_off_q = '0;
    assign req_offset = req_off_q;
    assign req_we     = 1'b0;
    assign req_wdata  = 32'd0;
    assign req_be     = 4'b1111;

    wire lanes_valid = (e_lanes == 8'd1) || (e_lanes == 8'd2) || (e_lanes == 8'd4) || (e_lanes == 8'h12);
    wire swap16 = (e_lanes == 8'h12);

    function automatic [1:0] lane_of(input [7:0] lanes, input [1:0] k);
        case (lanes)
            8'd2:    lane_of = {1'b0, k[1]};
            8'd4:    lane_of = k;
            default: lane_of = 2'd0;
        endcase
    endfunction

    wire [1:0] proc_idx  = swap16 ? {proc_k[1], ~proc_k[0]} : proc_k;   // swap16: bytes 1, 0, 3, 2
    wire [7:0] proc_byte = proc[31 - 8*proc_idx -: 8];
    wire [1:0] proc_lane = lane_of(e_lanes, proc_k);

    integer n;
    always @(posedge clk_sys) begin
        if (init || reset || restart) begin
            rstate <= R_IDLE; running <= 1'b0; done <= 1'b0; all_pass <= 1'b0;
            length_ok <= 1'b0; entry_status <= '0; outstanding <= 1'b0;
            hold_full <= 1'b0; proc_left <= '0; armed <= 1'b1;
            if (init) run_count <= '0;
        end else begin
            case (rstate)
            R_IDLE: if (armed && rom_loaded && record_ok) begin
                armed     <= 1'b0;
                running   <= 1'b1;
                done      <= 1'b0;
                length_ok <= ({5'd0, stream_bytes} == exp_len);
                entry     <= '0;
                fk        <= '0;
                rec_raddr <= RAW'(16);
                rstate    <= (entry_count == 0) ? R_DONE : R_FETCH;
            end

            R_FETCH: begin
                // rec_q holds word fk-1 of the entry; words 0..13 are used.
                fk <= fk + 5'd1;
                rec_raddr <= RAW'(16 + 16 * entry + fk + 1);
                case (fk)
                    5'd1:  begin e_region <= rec_q[3:0]; e_lanes <= rec_q[15:8]; end
                    5'd3:  e_offset[15:0]  <= rec_q;
                    5'd4:  e_offset[31:16] <= rec_q;
                    5'd5:  e_len[15:0]     <= rec_q;
                    5'd6:  e_len[31:16]    <= rec_q;
                    5'd7:  e_crc[0][15:0]  <= rec_q;
                    5'd8:  e_crc[0][31:16] <= rec_q;
                    5'd9:  e_crc[1][15:0]  <= rec_q;
                    5'd10: e_crc[1][31:16] <= rec_q;
                    5'd11: e_crc[2][15:0]  <= rec_q;
                    5'd12: e_crc[2][31:16] <= rec_q;
                    5'd13: e_crc[3][15:0]  <= rec_q;
                    5'd14: begin
                        e_crc[3][31:16] <= rec_q;
                        for (n = 0; n < 4; n++) crc[n] <= 32'hFFFFFFFF;
                        e_fail   <= 1'b0;
                        req_pos  <= '0;
                        req_off_q <= e_offset[25:0];
                        more_q   <= (e_len != 32'd0);            // = (0 < e_len)
                        done_pos <= '0;
                        entry_status[2*entry +: 2] <= 2'd1;
                        rstate   <= R_READ;
                    end
                    default: ;
                endcase
            end

            R_READ: begin
                if (!lanes_valid || e_offset[1:0] != 2'b00 || e_len[1:0] != 2'b00) begin
                    e_fail <= 1'b1;
                    rstate <= R_CMP;
                end else begin
                    if (req_valid && req_ready) begin
                        outstanding <= 1'b1;
                        req_pos     <= req_pos + 32'd4;
                        req_off_q   <= req_off_q + 26'd4;
                        more_q      <= (req_pos + 32'd4 < e_len);
                    end
                    if (outstanding && rsp_valid) begin
                        outstanding <= 1'b0;
                        hold        <= rsp_rdata;
                        hold_full   <= 1'b1;
                        if (rsp_err) e_fail <= 1'b1;
                    end
                    if (proc_left != 3'd0) begin
                        crc[proc_lane] <= crc32_byte(crc[proc_lane], proc_byte);
                        proc_k    <= proc_k + 2'd1;
                        proc_left <= proc_left - 3'd1;
                        done_pos  <= done_pos + 32'd1;
                    end else if (hold_full) begin
                        proc      <= hold;
                        proc_k    <= 2'd0;
                        proc_left <= 3'd4;
                        hold_full <= 1'b0;
                    end else if (done_pos == e_len && !outstanding) begin
                        rstate <= R_CMP;
                    end
                end
            end

            R_CMP: begin
                entry_status[2*entry +: 2] <=
                    (!e_fail &&
                     (~crc[0] == e_crc[0]) &&
                     (swap16 || e_lanes < 8'd2 || ~crc[1] == e_crc[1]) &&
                     (swap16 || e_lanes < 8'd4 || (~crc[2] == e_crc[2] && ~crc[3] == e_crc[3])))
                    ? 2'd2 : 2'd3;
                rstate <= R_NEXT;
            end

            R_NEXT: begin
                if (entry + 6'd1 >= entry_count) begin
                    rstate <= R_DONE;
                end else begin
                    entry     <= entry + 6'd1;
                    fk        <= '0;
                    rec_raddr <= RAW'(16 + 16 * (entry + 1));
                    rstate    <= R_FETCH;
                end
            end

            R_DONE: begin
                running  <= 1'b0;
                done     <= 1'b1;
                all_pass <= length_ok && (entry_count != 0) && !(|fail_bits(entry_status));
                run_count <= run_count + 4'd1;
                rstate   <= R_IDLE;       // armed=0: stays idle until reset/restart
            end

            default: rstate <= R_IDLE;
            endcase
        end
    end

    // Bit i set when entry i failed.
    function automatic [MAX_ENTRIES-1:0] fail_bits(input [2*MAX_ENTRIES-1:0] st);
        for (int i = 0; i < MAX_ENTRIES; i++) fail_bits[i] = (st[2*i +: 2] == 2'd3);
    endfunction
endmodule
