// Namco NB-2 MiSTer core -- board configuration record (MRA ioctl index 2, "NB2B" v1).
// Copyright (C) 2026 Kyle Lester. SPDX-License-Identifier: GPL-3.0-or-later
//
// The NB-1 core's nb1_board_config (docs/PROVENANCE.md) for the NB-2 record (docs/MRA_FORMAT.md). It describes
// the hardware fitted to a game's board; nothing here names a game. Generated by scripts/mra/nb2_mra.py.
//
// Record, 32 bytes, little-endian fields:
//   0-3   "NB2B"        4  version = 1      5  length = 32      6-7  0
//   8     KEYCUS mode (0 none, 1 ID word + changing word)        9  KEYCUS ID word index (0-15)
//   10-11 KEYCUS ID value                                        12 KEYCUS changing-word index (0-15)
//   13    bank transforms: bit 0 C123 pixel tile bits 6/8 swapped, bit 1 C123 tile bank,
//         bit 2 ROZ pixel tile bits 4/6 swapped, bit 3 sprite bank bitswap (6,4,3,1,2,0); bits 7-4 0
//   14    orientation (MAME ROT / 90)                            15 0
//   16-23 hot work-RAM pages: bit n = 4 KiB page $208000 + n * $1000 lives in block RAM (bits 63-57 0)
//   24-31 0
// The fields are taken only when the index-2 download ends and the whole record is valid (every download holds
// the CPUs in reset). No record or an invalid one: KEYCUS mode 0, no transforms, no hot pages (every work-RAM
// page in SDRAM: correct, only slower) -- the game then fails visibly at its KEYCUS check if it has one.
module nb2_board_config #(
    parameter [15:0] INDEX = 16'd2
) (
    input  wire        clk_sys,
    input  wire        init,

    input  wire        ioctl_download,
    input  wire [15:0] ioctl_index,
    input  wire        ioctl_wr,
    input  wire [26:0] ioctl_addr,
    input  wire [15:0] ioctl_dout,        // WIDE=1: [7:0] = byte at addr, [15:8] = byte at addr+1

    output reg         record_ok   = 1'b0,
    output reg         record_seen = 1'b0,
    output reg  [7:0]  kc_mode     = 8'd0,
    output reg  [3:0]  kc_id_word  = 4'd0,
    output reg  [15:0] kc_id       = 16'd0,
    output reg  [3:0]  kc_rnd_word = 4'd0,
    output reg  [3:0]  xform       = 4'd0,
    output reg  [1:0]  game_rot    = 2'd0,
    output reg  [56:0] hot_pages   = '0
);
    wire sel = ioctl_download && (ioctl_index == INDEX);
    reg  sel_q = 1'b0;

    reg [15:0] w [0:15];
    reg [15:0] got = 16'd0;

    wire hdr_ok = (w[0] == 16'h424E) && (w[1] == 16'h4232) &&      // "NB2B"
                  (w[2] == 16'h2001) && (w[3] == 16'h0000);       // version 1, length 32
    wire fld_ok = (w[4][7:0] <= 8'd1) && (w[4][15:12] == 4'd0) &&
                  (w[6][7:4] == 4'd0) && (w[6][15:12] == 4'd0) &&
                  (w[7][7:0] <= 8'd3) && (w[7][15:8] == 8'd0) &&
                  (w[11][15:9] == 7'd0) &&
                  (w[12] == 16'd0) && (w[13] == 16'd0) && (w[14] == 16'd0) && (w[15] == 16'd0);
    wire valid  = (got == 16'hFFFF) && hdr_ok && fld_ok;

    always @(posedge clk_sys) begin
        if (init) begin
            sel_q <= 1'b0; got <= 16'd0;
            record_ok <= 1'b0; record_seen <= 1'b0;
            kc_mode <= 8'd0; kc_id_word <= 4'd0; kc_id <= 16'd0; kc_rnd_word <= 4'd0;
            xform <= 4'd0; game_rot <= 2'd0; hot_pages <= '0;
        end else begin
            sel_q <= sel;
            if (sel && !sel_q) begin
                got       <= 16'd0;
                record_ok <= 1'b0;
                kc_mode   <= 8'd0;
            end
            if (sel && ioctl_wr && ioctl_addr[26:5] == 22'd0) begin
                w[ioctl_addr[4:1]]   <= ioctl_dout;
                got[ioctl_addr[4:1]] <= 1'b1;
            end
            if (!sel && sel_q) begin
                record_seen <= 1'b1;
                record_ok   <= valid;
                kc_mode     <= valid ? w[4][7:0]   : 8'd0;
                kc_id_word  <= valid ? w[4][11:8]  : 4'd0;
                kc_id       <= valid ? w[5]        : 16'd0;
                kc_rnd_word <= valid ? w[6][3:0]   : 4'd0;
                xform       <= valid ? w[6][11:8]  : 4'd0;
                game_rot    <= valid ? w[7][1:0]   : 2'd0;
                hot_pages   <= valid ? {w[11][8:0], w[10], w[9], w[8]} : '0;
            end
        end
    end
endmodule
